%%%-------------------------------------------------------------------
%% @doc
%%  Cessor Information Systems, CIS
%%  CIS License v0.1.0
%%  https://cessor.org
%%  Cessor Service Transaction Protocol
%%  Version Crown-Block index = 0
%%  Version Serial Domain = 0
%%  Version Serial Number = 0
%%  Service Domain = 0;         System service domain
%%  Service Sub-Domain = 0;     System service sub-domain
%%  Procedure Range = 3;        Gate Procedure Packages Range
%%  Procedure Package = 3;      Interface_remote package
%% @end
%%%-------------------------------------------------------------------
-module(cstp_000000_0000_0303).

-export([compose/2]).
-export([compute/2]).

-import(cstp_ft, [ft/2]).
%%%%%%%%%%%%%%%
%%   EXPORT  %%
%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%
%%   Compose CSTX  %%
%%%%%%%%%%%%%%%%%%%%%
%%
%% compose({Order, TX}, STATE)-> Result
%%  Order = list of tuples, [Process | Rest]
%%          Process = tuple of numbers, {PM, Processor}
%%                    PM = number, >=0 && <256, process module
%%                    Processor = number, >=0 && <256, process ID
%%          Rest = list of tuples, [ Parameters ]
%%  TX = binary, recursive composed TX
%%  STATE = map, state of caller has to be compatible with order resources
%%  Result =
%%      {ok,TX_}
%%          TX_ = binary, recursive composed TX
%%                      
%%      {error,  Reason}
%%          Generated by Fault Tolerance
%%            ft(Issuer, Fault) 
%%              Issuer = compose
%%              Fault =
%%                {error, [order]}, order format is unavailable
%% INFO:
%%      Compose a cessor cervice transaction, CSTX from an order list
%%      This module composes orders with Version {CBI=0, VSD=0, VSN=0}
%%      This module composes orders with Service {SD=0, SSD=0}
%%      This module composes orders with Procedure {PR=3, PP=3}
%%      Process Module PM=0; is reserved for State Process Module
%%
compose({Order=[{_module=0,_} | _rest], TX}, STATE) ->
    cstp_000000_0000_0303_00:compose({Order, <<TX/binary, 0>>}, STATE);
compose({Order=[{_module=1,_} | _rest], TX}, STATE) ->
  cstp_000000_0000_0303_01:compose({Order, <<TX/binary, 1>>}, STATE);
compose(_Order, _STATE) ->
    ft(_Issuer={?MODULE, compose}, _Fault={error, [order]}).
%%%%%%%%%%%%%%%%%%%%%
%%   Compute CSTX  %%
%%%%%%%%%%%%%%%%%%%%%
%%
%% compute(TX, STATE)-> Result
%%  TX = binary, << Process, Rest >>
%%          Process = binary, << PM, Processor >>
%%                    PM = number, >=0 && <256, process module
%%                    Processor = number, >=0 && <256, process ID
%%          Rest = binary, << Process, Parameters >>
%%  STATE = map, state of caller has to be compatible with the resources needed to compute TX
%%  Result =
%%      {ok,Call_back}
%%          Call_back = term
%%                      
%%      {error,  Reason}
%%          Reason = generated by Fault Tolerance
%%            ft(Issuer, Fault) 
%%              Issuer = compute
%%              Fault =
%%                {error, [tx]}, Tx format is not available
%% INFO:
%%      Compute a cessor cervice transaction, CSTX
%%      Process Module PM=0; is reserved for State Process Module
%%
compute(<<Module, TX_/binary>>, STATE)
  when Module == 0->
    cstp_000000_0000_0303_00:compute(TX_, STATE);

compute(<<Module, TX_/binary>>, STATE)
  when Module == 1->
    cstp_000000_0000_0303_01:compute(TX_, STATE);

compute(_TX, _STATE) ->
  ft(_Issuer={?MODULE, compute},_Fault={error, [tx]}).
  
  %%%%%%%%%%%%%%%%%
  %%   INTERNAL  %%
  %%%%%%%%%%%%%%%%%