%%%-------------------------------------------------------------------
%% @doc
%%  Cessor Information Systems, CIS
%%  CIS License v0.1.0
%%  https://cessor.org
%%  Cessor Service Transaction Protocol
%%  Version Crown-Block index = 0
%%  Version Serial Domain = 0
%%  Version Serial Number = 0
%%  Service Domain = 0;         System service domain
%%  Service Sub-Domain = 0;     System service sub-domain
%%  Procedure Range = 3;        Gate Procedure Packages Range
%%  Procedure Package = 0;      Interface package
%%  Process Module = 0;         State Process Module
%% @end
%%%-------------------------------------------------------------------
-module(cstp_000000_0000_0300_00).

-export([compose/2]).
-export([compute/2]).

-import(cstp_ft, [ft/2]).
%%%%%%%%%%%%%%%
%%   EXPORT  %%
%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%
%%   Compose CSTX  %%
%%%%%%%%%%%%%%%%%%%%%
%%
%% compose({Order, TX}, STATE)-> Result
%%  Order = list of tuples, [Process | Rest]
%%          Process = tuple of numbers, {PM, Processor_ref}
%%                    PM = number, >=0 && <256, process module
%%                    Processor_ref = number, >=0 && <256, process ID
%%          Rest = list of tuples, [ Parameters ]
%%  TX = binary, recursive composed TX
%%  STATE = map, state of caller has to be compatible with order resources
%%  Result =
%%      {ok,TX_}
%%          TX_ = binary, recursive composed TX
%%                      
%%      {error,  Reason}
%%          Generated by Fault Tolerance
%%            ft(Issuer, Fault) 
%%              Issuer = compose
%%              Fault =
%%                {error, [order]}, order format is unavailable
%% INFO:
%%      Compose a cessor cervice transaction, CSTX from an order list
%%      This module composes orders with Version {CBI=0, VSD=0, VSN=0}
%%      This module composes orders with Service {SD=0, SSD=0}
%%      This module composes orders with Procedure {PR=3, PP=0}
%%      This module composes orders with Process Module PM=0
%%      Processor reference pRef=0; is reserved for INIT Processor
%%      Processor reference pRef=1; is reserved for BOOT Processor
%%      Processor reference pRef=2; is reserved for STATUS Processor
%%      Compose caller can be every processes id, PID
%%
compose({[{_module=0, _ref=0}], TX}, STATE) ->
    processor_ref0({compose, TX}, STATE);
compose({[{_module=0, _ref=1}], TX}, STATE) ->
    processor_ref1({compose, TX}, STATE);
compose({[{_module=0, _ref=2}], TX}, STATE) ->
    processor_ref2({compose, TX}, STATE);

compose(Order, _STATE) ->
    ft(_Issuer={?MODULE, compose}, _Fault={error, [{order, Order}]}).
%%%%%%%%%%%%%%%%%%%%%
%%   Compute CSTX  %%
%%%%%%%%%%%%%%%%%%%%%
%%
%% compute(TX, STATE)-> Result
%%  TX = binary, << Process, Rest >>
%%          Process = binary, << Processor_ref >>
%%                    Processor_ref = number, >=0 && <256, process ID
%%          Rest = binary, << Parameters >>
%%  STATE = map, state of caller has to be compatible with the resources needed to compute TX
%%  Result =
%%      {ok,Call_back}
%%          Call_back = term
%%                      
%%      {error,  Reason}
%%          Reason = generated by Fault Tolerance
%%            ft(Issuer, Fault) 
%%              Issuer = compute
%%              Fault =
%%                {error, [permission]}, Caller has no permission
%% INFO:
%%      Compute a cessor cervice transaction, CSTX
%%      Processor reference pRef=0 has to be called by core application
%%      Processor reference pRef=k has to be called by interface generic server
%%
compute(TX= <<0, _/binary>>, STATE)->
    case whereis(core) == self() of
        true ->
            compute(parse, TX, STATE);
        false ->
            ft(_Issuer={?MODULE, compute}, _Fault={error, [permission]})
    end;
compute(TX, STATE)->
    case whereis(interface) == self() of
        true ->
            compute(parse, TX, STATE);
        false ->
            ft(_Issuer={?MODULE, compute}, _Fault={error, [permission]})
    end.

%%%%%%%%%%%%%%%%%
%%   INTERNAL  %%
%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Parse Processor Reference Information %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%
%% compute({parse, TX}, STATE)-> Result
%%  TX = binary, << Process, Rest >>
%%          Process = binary, << Processor_ref >>
%%                    Processor_ref = number, >=0 && <256, process ID
%%          Rest = binary, << Parameters >>
%%  STATE = map, state of caller has to be compatible with the resources needed to compute TX
%%  Result =
%%      Result of processor_ref*k/2
%%                      
%%      {error,  Reason}
%%          Reason = generated by Fault Tolerance
%%            ft(Issuer, Fault) 
%%              Issuer = compute
%%              Fault =
%%                {error, [parse]}, Tx format is not available
%% INFO:
%%      Compute a cessor cervice transaction, CSTX
%%      Parse Processor References to compute
%%      Processor reference pRef=0; is reserved for INIT Processor
%%      Processor reference pRef=1; is reserved for BOOT Processor
%%      Processor reference pRef=2; is reserved for STATUS Processor
%%
compute(parse, <<0, TX_/binary>>, STATE)->
    processor_ref0({compute, TX_}, STATE);
compute(parse, <<1, TX_/binary>>, STATE)->
    processor_ref1({compute, TX_}, STATE);
compute(parse, <<2, TX_/binary>>, STATE)->
    processor_ref2({compute, TX_}, STATE);
compute(parse, _TX, _STATE) ->
    ft(_Issuer={?MODULE, compute}, _Fault={error, [parse]}).

%%%%%%%%%%%%%%%%%%%%%%%%%
%%   State Processors  %%
%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%%%%%
%%   INIT Processor  %%
%%%%%%%%%%%%%%%%%%%%%%%
%%
%% processor_ref0({compose, TX}, _)-> Result
%%  TX = binary, recursive composed TX
%%  
%%  Result =
%%      {ok,TX_}
%%          TX_ = binary, recursive composed TX
%% INFO:
%%      Compose CSTX for processor_ref0
%%      A set of tasks to init the state of core generic server
%%
%%  A set of tasks to setup the system Database.
%%  The DB is OTP/mnesia DBMS
%%
processor_ref0({compose, TX}, _STATE)->
    {ok, <<TX/binary, 0>>};
%%
%% processor_ref0({compute, TX}, _)-> Result
%%  TX = binary, <<  >>
%%  
%%  Result =
%%      {ok,New_state}
%%          New_state = map, updated state of core generic server
%%      {error, Reason :: term()}
%% INFO:
%%      Compute CSTX
%%      Start and link new interface generic server
%%
processor_ref0({compute, <<>>}, Core_state)->
    case interface:start_link() of
        {ok, PID} ->
            SYS_services = maps:get(service, Core_state),
            New_services = lists:keyreplace(gate, 1, SYS_services, {gate ,PID, init}),
            New_state = maps:update(service, New_services, Core_state),
            {ok, New_state};
        {error, Reason} ->
            ft(_Issuer={?MODULE, processor_ref0}, _Fault={error, [Reason]})
    end;
%%
%% processor_ref0(_,_)-> Result
%%  Result =
%%      {error,  Reason}
%%          Reason = generated by Fault Tolerance
%%            ft(Issuer, Fault) 
%%              Issuer = processor_ref0
%%              Fault =
%%                {error, [tx]}, Tx format is not available
%% INFO:
%%      Computation is failed because of unavailable arguments
%%
processor_ref0(_,_) ->
    ft(_Issuer={?MODULE, processor_ref0}, _Fault={error, [tx]}).

%%%%%%%%%%%%%%%%%%%%%%%
%%   BOOT Processor  %%
%%%%%%%%%%%%%%%%%%%%%%%
%%
%% processor_ref1({compose, TX}, _)-> Result
%%  TX = binary, recursive composed TX
%%  
%%  Result =
%%      {ok,TX_}
%%          TX_ = binary, recursive composed TX
%% INFO:
%%      Compose CSTX for processor_ref1
%%      A set of tasks to setup system services of core generic server
%%
processor_ref1({compose, TX}, _STATE)->
    {ok, <<TX/binary, 1>>};
%%
%% processor_ref1({compute, TX}, STATE)-> Result
%%  TX = binary, << >>
%%  STATE = map, Interface STATE
%%  
%%  Result =
%%      {ok,New_state}
%%          New_state = map, the updated STATE
%%      {error, Reason :: term()}
%% INFO:
%%      Compute CSTX
%%      Run components
%%      Start and link new interface_port generic server
%%
processor_ref1({compute, <<>>}, STATE)->
    TX_port = [
        {0,0,0},    %version
        {0,0},      %service:system services
        {3,1},      %procedure:gate pRange, interface_port pPack
        {0,0}       %process:state pMod, INIT pRef
    ],
    {ok, CSTX_port} = cstp:compose(TX_port, #{}),
    io:format("CSTX_port: ~p~n", [CSTX_port]),
    Ref_port = make_ref(),
    gen_server:cast(self(), {Ref_port, CSTX_port}),

    New_ref = [Ref_port],
    Proc_ref = maps:get(proc_ref, STATE) ++ New_ref,
    New_state = maps:update(proc_ref, Proc_ref, STATE),
    {ok, New_state};
%%
%% processor_ref1(_,_)-> Result
%%  Result =
%%      {error,  Reason}
%%          Reason = generated by Fault Tolerance
%%            ft(Issuer, Fault) 
%%              Issuer = processor_ref0
%%              Fault =
%%                {error, [tx]}, Tx format is not available
%% INFO:
%%      Computation is failed because of unavailable arguments
%%
processor_ref1(_,_) ->
    ft(_Issuer={?MODULE, processor_ref1}, _Fault={error, [tx]}).

%%%%%%%%%%%%%%%%%%%%%%%%%
%%   STATUS Processor  %%
%%%%%%%%%%%%%%%%%%%%%%%%%
%%
%% processor_ref2({compose, TX}, _)-> Result
%%  TX = binary, recursive composed TX
%%  
%%  Result =
%%      {ok,TX_}
%%          TX_ = binary, recursive composed TX
%% INFO:
%%      Compose CSTX for processor_ref2
%%      A recursive composed TX
%%
processor_ref2({compose, TX}, _STATE)->
    {ok, <<TX/binary, 2>>};
%%
%% processor_ref2({compute, TX}, _)-> Result
%%  TX = binary, << PIN >>
%%  
%%  Result =
%%      {ok,New_state}
%%          New_state = map, the updated STATE
%%      {error, Reason :: term()}
%% INFO:
%%      Compose CSTX for processor_ref2
%%      A set of tasks to report system serviceses state and interpret new status
%%      If need upgrade the service status and propogate it
%%
processor_ref2({compute, <<>>}, STATE)->
    Report = processor_ref2({status, report}, STATE),
    processor_ref2({interpret, Report}, STATE);


processor_ref2({status, report}, STATE)->
    Services = maps:get(service, STATE),
    %%  STATUS unset, init, ready, challenge, problem
    Statuses =
        [
            {unset, []},
            {init, []},
            {boot, []},
            {ready, []}
            %%  Other statuses
        ],
    Fun =
        fun
            ({Name, _pid, unset}, Report) ->    %%  UNSET
                {unset, UNSET} = lists:keyfind(unset, 1, Report),
                lists:keyreplace(
                    unset
                    ,1
                    ,Report
                    ,{boot,UNSET++[Name]}
                );
            ({Name, _pid, init}, Report) ->    %% INIT
                {init, INIT} = lists:keyfind(init, 1, Report),
                lists:keyreplace(
                    init
                    ,1
                    ,Report
                    ,{init,INIT++[Name]}
                );
            ({Name, _pid, boot}, Report) ->    %% BOOT
                {boot, BOOT} = lists:keyfind(boot, 1, Report),
                lists:keyreplace(
                    boot
                    ,1
                    ,Report
                    ,{boot,BOOT++[Name]}
                );
            ({Name, _pid, ready}, Report) ->    %%  READY
                {ready, READY} = lists:keyfind(ready, 1, Report),
                lists:keyreplace(
                    ready
                    ,1
                    ,Report
                    ,{ready,READY++[Name]}
                )
        end,
    lists:foldl(Fun, Statuses, Services);

processor_ref2({interpret, Report}, STATE)->
    %   List of services with status of UNSET
    %{unset, UNSET} = lists:keyfind(unset, 1, Report),
    %   List of services with status of INIT
    {init, _INIT} = lists:keyfind(init, 1, Report),
    %   List of services with status of BOOT
    {boot, BOOT} = lists:keyfind(boot, 1, Report),
    %   List of services with status of READY
    {ready, READY} = lists:keyfind(ready, 1, Report),
    Services_len = length(maps:get(service, STATE)),

    case maps:get(status, STATE) of
        init
            when Services_len == length(BOOT)->
                STATUS = <<"BOOT">>,
                Broad_list = [cold_state, core],
                processor_ref2({broadcast, STATUS, Broad_list}, STATE);
        boot
            when Services_len == length(READY)->
                STATUS = <<"READY">>,
                Broad_list = [],
                processor_ref2({broadcast, STATUS, Broad_list}, STATE);
        _ ->
            {ok, STATE}
    end;

processor_ref2({broadcast, STATUS, Broad_list}, STATE)->
    Broadcast =
        fun
            (cold_state, ok) ->
                processor_ref2({cold_state, STATUS}, STATE);
            (Name, ok) ->
                processor_ref2({call, Name, STATUS}, STATE);
            (_,ERR) ->
                ERR
        end,
    case lists:foldl(Broadcast, ok, Broad_list) of
        ok->
            STATE_status = maps:update(status, STATUS, STATE),
            {ok, STATE_status};
        ERR->
            ft(_Issuer={?MODULE, processor_ref2},
                _Fault={error, [broadcast]++ERR})
    end;
processor_ref2({cold_state, STATUS}, STATE) ->
    COLD_STATUS =
        case STATUS of
            <<"BOOT">> -> <<2>>
        end,
    TX_coldState = [
        {0,0,0},    %version
        {0,0},      %service:system services
        {3,3},      %procedure:gate pRange, interface_remote pPack
        {1,0}       %process:call pMod, System STATUS pRef
        , COLD_STATUS
    ],
    {ok, CSTX_coldState} = cstp:compose(TX_coldState, STATE),
    Path = filename:join(["services", "system", "gate", "state", "INTERFACE"]),
    file:write_file(Path, CSTX_coldState);
processor_ref2({call, Name, STATUS}, STATE) ->
    {Procedure, PID} =
        case Name of
            core ->     {{0,0}, whereis(core)};
            crypto ->   {{1,0}, whereis(crypto_man)};
            store ->    {{2,0}, whereis(storage)};
            gate ->     {{3,0}, whereis(interface)}
        end,
    TX = [
        {0,0,0},        %version
        {0,0},          %service:system services
        Procedure,      %procedure: {pRange, pPack}
        {1,0}           %process:call pMod, System STATUS pRef
        , STATUS        %status:STATUS
    ],
    {ok, CSTX} = cstp:compose(TX, STATE),
    try
        gen_server:call(PID, CSTX)
    catch
        exit:_ ->
            {error, [call, Name]}
    end;
%%
%% processor_ref2(_,_)-> Result
%%  Result =
%%      {error,  Reason}
%%          Reason = generated by Fault Tolerance
%%            ft(Issuer, Fault) 
%%              Issuer = processor_ref2
%%              Fault =
%%                {error, [tx]}, Tx format is not available
%% INFO:
%%      Computation is failed because of unavailable arguments
%%
processor_ref2(_,_) ->
    ft(_Issuer={?MODULE, processor_ref2}, _Fault={error, [tx]}).